version: "3.9"

services:
  backend:
    build: ./backend
    container_name: renode_backend
    network_mode: "host"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: renode_frontend
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://10.10.0.1:8000
      - NEXT_PUBLIC_BACKEND_URL=http://10.10.0.1:8000
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=supersecretkey123
    depends_on:
      - backend
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start
      "
    # networks:
    #   - renode-net

# networks:
#   renode-net:
#     driver: bridge